sonar.projectKey=financi-backend
sonar.projectName=Financi Backend
sonar.sources=src
sonar.tests=test
sonar.test.inclusions=test/**/*.test.ts
sonar.exclusions=node_modules/**,dist/**,coverage/**,.stryker-tmp/**,reports/**
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
